#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Actuator_P_Galatea

#include "Basic.hpp"


namespace SDK::Params
{

// Function Actuator_P_Galatea.Actuator_P_Galatea_C.ExecuteUbergraph_Actuator_P_Galatea
// 0x0004 (0x0004 - 0x0000)
struct Actuator_P_Galatea_C_ExecuteUbergraph_Actuator_P_Galatea final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Actuator_P_Galatea_C_ExecuteUbergraph_Actuator_P_Galatea;

}

