#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Actuator_P_Yvette_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Actuator_P_Yvette.Actuator_P_Yvette_C
// 0x0010 (0x07A0 - 0x0790)
class Actuator_P_Yvette_0::AActuator_P_Yvette_C final : public ACySummonActor
{
public:
	class BP_ActuatorComponent_P_Yvette::UBP_ActuatorComponent_P_Yvette_C* BP_ActuatorComponent_P_Yvette; // 0x0790(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0798(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Actuator_P_Yvette.Actuator_P_Yvette_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Actuator_P_Yvette_C")
	}
	static class Actuator_P_Yvette_0::AActuator_P_Yvette_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Actuator_P_Yvette_0::AActuator_P_Yvette_C>();
	}
};
DUMPER7_ASSERTS_Actuator_P_Yvette_0__AActuator_P_Yvette_C;

}

