#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Actuator_P_Fragrans_0

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Actuator_P_Fragrans.Actuator_P_Fragrans_C
// 0x0020 (0x07B0 - 0x0790)
class Actuator_P_Fragrans_0::AActuator_P_Fragrans_C final : public ACySummonActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0790(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCySearchTargetsComponent*              CySearchTargets;                                   // 0x0798(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyActuatorComponent*                   CyActuator;                                        // 0x07A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x07A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void ExecuteUbergraph_Actuator_P_Fragrans(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Actuator_P_Fragrans.Actuator_P_Fragrans_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Actuator_P_Fragrans_C")
	}
	static class Actuator_P_Fragrans_0::AActuator_P_Fragrans_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Actuator_P_Fragrans_0::AActuator_P_Fragrans_C>();
	}
};
DUMPER7_ASSERTS_Actuator_P_Fragrans_0__AActuator_P_Fragrans_C;

}

