#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Actuator_P_Flavia

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Actuator_P_Flavia.Actuator_P_Flavia_C
// 0x0020 (0x0860 - 0x0840)
class Actuator_P_Flavia::AActuator_P_Flavia_C final : public ACySummonActor
{
public:
	uint8                                         Pad_838[0x8];                                      // 0x0838(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UCyActuatorComponent*                   CyActuator;                                        // 0x0840(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyAccumulatorComponent*                CyAccumulator;                                     // 0x0848(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0850(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Actuator_P_Flavia.Actuator_P_Flavia_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Actuator_P_Flavia_C")
	}
	static class Actuator_P_Flavia::AActuator_P_Flavia_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Actuator_P_Flavia::AActuator_P_Flavia_C>();
	}
};
DUMPER7_ASSERTS_Actuator_P_Flavia__AActuator_P_Flavia_C;

}

