#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_LayerSetup

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ALI_LayerSetup.ALI_LayerSetup_C
// 0x0000 (0x0000 - 0x0000)
class IALI_LayerSetup_C final
{
public:
	void SetupLayer(const struct FPoseLink& BasePose, const struct FPoseLink& BlendPose, struct FPoseLink* SetupLayer_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ALI_LayerSetup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ALI_LayerSetup_C")
	}
	static class IALI_LayerSetup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IALI_LayerSetup_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IALI_LayerSetup_C;

}

