#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_LayerSetup

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function ALI_LayerSetup.ALI_LayerSetup_C.SetupLayer
// 0x0030 (0x0030 - 0x0000)
struct ALI_LayerSetup_C_SetupLayer final
{
public:
	struct FPoseLink                              BasePose;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              BlendPose;                                         // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              SetupLayer_0;                                      // 0x0020(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ALI_LayerSetup_C_SetupLayer;

}

