#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Chiyo_Cloth_Physics

#include "Basic.hpp"

#include "AnimBP_Chiyo_Cloth_Physics_classes.hpp"
#include "AnimBP_Chiyo_Cloth_Physics_parameters.hpp"


namespace SDK
{

// Function AnimBP_Chiyo_Cloth_Physics.AnimBP_Chiyo_Cloth_Physics_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 BaseLayerInput                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// const struct FPoseLink&                 OverlayLayerInput                                      (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_Chiyo_Cloth_Physics_C::AnimGraph(const struct FPoseLink& BaseLayerInput, const struct FPoseLink& OverlayLayerInput, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Chiyo_Cloth_Physics_C", "AnimGraph");

	Params::AnimBP_Chiyo_Cloth_Physics_C_AnimGraph Parms{};

	Parms.BaseLayerInput = std::move(BaseLayerInput);
	Parms.OverlayLayerInput = std::move(OverlayLayerInput);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_Chiyo_Cloth_Physics.AnimBP_Chiyo_Cloth_Physics_C.ExecuteUbergraph_AnimBP_Chiyo_Cloth_Physics
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_Chiyo_Cloth_Physics_C::ExecuteUbergraph_AnimBP_Chiyo_Cloth_Physics(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Chiyo_Cloth_Physics_C", "ExecuteUbergraph_AnimBP_Chiyo_Cloth_Physics");

	Params::AnimBP_Chiyo_Cloth_Physics_C_ExecuteUbergraph_AnimBP_Chiyo_Cloth_Physics Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

