#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Kanami_101_Physics

#include "Basic.hpp"

#include "AnimBP_Kanami_101_Physics_classes.hpp"
#include "AnimBP_Kanami_101_Physics_parameters.hpp"


namespace SDK
{

// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 Input                                                  (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_Kanami_101_Physics_C::AnimGraph(const struct FPoseLink& Input, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "AnimGraph");

	Params::AnimBP_Kanami_101_Physics_C_AnimGraph Parms{};

	Parms.Input = std::move(Input);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_82514A6E41CA7B51C3069F9777DF8194
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_82514A6E41CA7B51C3069F9777DF8194()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_82514A6E41CA7B51C3069F9777DF8194");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_69BA7AD9454303549FD6758976D00176
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_69BA7AD9454303549FD6758976D00176()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_69BA7AD9454303549FD6758976D00176");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_48AFB1C141565E24D62C79A6166661BD
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_48AFB1C141565E24D62C79A6166661BD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_48AFB1C141565E24D62C79A6166661BD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_ECE8E42B4B633B12C44F7EA92E324921
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_ECE8E42B4B633B12C44F7EA92E324921()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_ECE8E42B4B633B12C44F7EA92E324921");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_4A0637A443F0CFB3A58B89903E72EEB9
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_4A0637A443F0CFB3A58B89903E72EEB9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_4A0637A443F0CFB3A58B89903E72EEB9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_2D5A15F34694E3BBCDD24A827C357469
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_2D5A15F34694E3BBCDD24A827C357469()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_2D5A15F34694E3BBCDD24A827C357469");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_0856120040604F578B7001944F402E3B
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_0856120040604F578B7001944F402E3B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_0856120040604F578B7001944F402E3B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_B0FA21FB4C7DDAD91C88B0B4A00C591B
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_B0FA21FB4C7DDAD91C88B0B4A00C591B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_B0FA21FB4C7DDAD91C88B0B4A00C591B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_C97FDF3742C68B4FB5285FA99EE84B29
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_C97FDF3742C68B4FB5285FA99EE84B29()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_C97FDF3742C68B4FB5285FA99EE84B29");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_39A1BBC141158E9E3E63B09EA7C63A03
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_39A1BBC141158E9E3E63B09EA7C63A03()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_39A1BBC141158E9E3E63B09EA7C63A03");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_49EBF8D3427649222FAA399F5C2DBE99
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_49EBF8D3427649222FAA399F5C2DBE99()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_49EBF8D3427649222FAA399F5C2DBE99");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_0F2CAF84419599A7606188B5A0962A69
// (BlueprintEvent)

void UAnimBP_Kanami_101_Physics_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_0F2CAF84419599A7606188B5A0962A69()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Kanami_101_Physics_AnimGraphNode_KawaiiPhysics_0F2CAF84419599A7606188B5A0962A69");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_Kanami_101_Physics.AnimBP_Kanami_101_Physics_C.ExecuteUbergraph_AnimBP_Kanami_101_Physics
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_Kanami_101_Physics_C::ExecuteUbergraph_AnimBP_Kanami_101_Physics(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Kanami_101_Physics_C", "ExecuteUbergraph_AnimBP_Kanami_101_Physics");

	Params::AnimBP_Kanami_101_Physics_C_ExecuteUbergraph_AnimBP_Kanami_101_Physics Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

