#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_FAMAS_108_Physics

#include "Basic.hpp"

#include "AnimBP_FAMAS_108_Physics_classes.hpp"
#include "AnimBP_FAMAS_108_Physics_parameters.hpp"


namespace SDK
{

// Function AnimBP_FAMAS_108_Physics.AnimBP_FAMAS_108_Physics_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_FAMAS_108_Physics_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_FAMAS_108_Physics_C", "AnimGraph");

	Params::AnimBP_FAMAS_108_Physics_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_FAMAS_108_Physics.AnimBP_FAMAS_108_Physics_C.ExecuteUbergraph_AnimBP_FAMAS_108_Physics
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_FAMAS_108_Physics_C::ExecuteUbergraph_AnimBP_FAMAS_108_Physics(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_FAMAS_108_Physics_C", "ExecuteUbergraph_AnimBP_FAMAS_108_Physics");

	Params::AnimBP_FAMAS_108_Physics_C_ExecuteUbergraph_AnimBP_FAMAS_108_Physics Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

