#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AC_EndSmite

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AC_EndSmite.BP_AC_EndSmite_C
// 0x0000 (0x04E8 - 0x04E8)
class UBP_AC_EndSmite_C final : public UCyGPActionContainer
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AC_EndSmite_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AC_EndSmite_C")
	}
	static class UBP_AC_EndSmite_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AC_EndSmite_C>();
	}
};
DUMPER7_ASSERTS_UBP_AC_EndSmite_C;

}

