#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Atom_Revival

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Atom_Revival.BP_Atom_Revival_C
// 0x0000 (0x0610 - 0x0610)
class BP_Atom_Revival::UBP_Atom_Revival_C final : public UCySAtomRevival
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Atom_Revival.BP_Atom_Revival_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Atom_Revival_C")
	}
	static class BP_Atom_Revival::UBP_Atom_Revival_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Atom_Revival::UBP_Atom_Revival_C>();
	}
};
DUMPER7_ASSERTS_BP_Atom_Revival__UBP_Atom_Revival_C;

}

