#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ApplyEffect_Q_Mara_AddArmor

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ApplyEffect_Q_Mara_AddArmor.BP_ApplyEffect_Q_Mara_AddArmor_C
// 0x0000 (0x05D0 - 0x05D0)
class UBP_ApplyEffect_Q_Mara_AddArmor_C final : public UCySAtomApplyEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ApplyEffect_Q_Mara_AddArmor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ApplyEffect_Q_Mara_AddArmor_C")
	}
	static class UBP_ApplyEffect_Q_Mara_AddArmor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ApplyEffect_Q_Mara_AddArmor_C>();
	}
};
DUMPER7_ASSERTS_UBP_ApplyEffect_Q_Mara_AddArmor_C;

}

