#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AtomPlayEffect_FirstHit

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AtomPlayEffect_FirstHit.BP_AtomPlayEffect_FirstHit_C
// 0x0000 (0x05D0 - 0x05D0)
class UBP_AtomPlayEffect_FirstHit_C final : public UCySAtomPlayAsset_BeamTarget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AtomPlayEffect_FirstHit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AtomPlayEffect_FirstHit_C")
	}
	static class UBP_AtomPlayEffect_FirstHit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AtomPlayEffect_FirstHit_C>();
	}
};
DUMPER7_ASSERTS_UBP_AtomPlayEffect_FirstHit_C;

}

