#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Atom_InterceptTarget

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Atom_InterceptTarget.BP_Atom_InterceptTarget_C
// 0x0000 (0x0618 - 0x0618)
class UBP_Atom_InterceptTarget_C final : public UCySAtomInterceptTarget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Atom_InterceptTarget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Atom_InterceptTarget_C")
	}
	static class UBP_Atom_InterceptTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Atom_InterceptTarget_C>();
	}
};
DUMPER7_ASSERTS_UBP_Atom_InterceptTarget_C;

}

