#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Character_Michele

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Character_Michele.BP_Character_Michele_C.ExecuteUbergraph_BP_Character_Michele
// 0x0004 (0x0004 - 0x0000)
struct BP_Character_Michele_C_ExecuteUbergraph_BP_Character_Michele final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Character_Michele_C_ExecuteUbergraph_BP_Character_Michele;

}

