#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Calculatio_Knife_AddHealth_Q_Mara

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Calculatio_Knife_AddHealth_Q_Mara.BP_Calculatio_Knife_AddHealth_Q_Mara_C
// 0x0000 (0x0128 - 0x0128)
class UBP_Calculatio_Knife_AddHealth_Q_Mara_C final : public UCyCalculationDamage
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Calculatio_Knife_AddHealth_Q_Mara_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Calculatio_Knife_AddHealth_Q_Mara_C")
	}
	static class UBP_Calculatio_Knife_AddHealth_Q_Mara_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Calculatio_Knife_AddHealth_Q_Mara_C>();
	}
};
DUMPER7_ASSERTS_UBP_Calculatio_Knife_AddHealth_Q_Mara_C;

}

