#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DamageAccumulator_Michele_P_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DamageAccumulator_Michele_P.BP_DamageAccumulator_Michele_P_C
// 0x0000 (0x0380 - 0x0380)
class BP_DamageAccumulator_Michele_P_0::UBP_DamageAccumulator_Michele_P_C final : public UCyDamageAccumulator
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_DamageAccumulator_Michele_P.BP_DamageAccumulator_Michele_P_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DamageAccumulator_Michele_P_C")
	}
	static class BP_DamageAccumulator_Michele_P_0::UBP_DamageAccumulator_Michele_P_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_DamageAccumulator_Michele_P_0::UBP_DamageAccumulator_Michele_P_C>();
	}
};
DUMPER7_ASSERTS_BP_DamageAccumulator_Michele_P_0__UBP_DamageAccumulator_Michele_P_C;

}

