#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DisplayActor_HealTargetLocked

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DisplayActor_HealTargetLocked.BP_DisplayActor_HealTargetLocked_C
// 0x0010 (0x0398 - 0x0388)
class BP_DisplayActor_HealTargetLocked::ABP_DisplayActor_HealTargetLocked_C final : public ACyDisplayWorldReticle
{
public:
	class UBP_CommonOverheadComponent_C*          Reticle;                                           // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_DisplayActor_HealTargetLocked.BP_DisplayActor_HealTargetLocked_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DisplayActor_HealTargetLocked_C")
	}
	static class BP_DisplayActor_HealTargetLocked::ABP_DisplayActor_HealTargetLocked_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_DisplayActor_HealTargetLocked::ABP_DisplayActor_HealTargetLocked_C>();
	}
};
DUMPER7_ASSERTS_BP_DisplayActor_HealTargetLocked__ABP_DisplayActor_HealTargetLocked_C;

}

