#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DamageType_Q_Kanami

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DamageType_Q_Kanami.BP_DamageType_Q_Kanami_C
// 0x0000 (0x05B0 - 0x05B0)
class BP_DamageType_Q_Kanami::UBP_DamageType_Q_Kanami_C final : public UPMDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_DamageType_Q_Kanami.BP_DamageType_Q_Kanami_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DamageType_Q_Kanami_C")
	}
	static class BP_DamageType_Q_Kanami::UBP_DamageType_Q_Kanami_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_DamageType_Q_Kanami::UBP_DamageType_Q_Kanami_C>();
	}
};
DUMPER7_ASSERTS_BP_DamageType_Q_Kanami__UBP_DamageType_Q_Kanami_C;

}

