#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DestroySummon_P_Yugiri

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DestroySummon_P_Yugiri.BP_DestroySummon_P_Yugiri_C
// 0x0000 (0x0250 - 0x0250)
class UBP_DestroySummon_P_Yugiri_C final : public UCyGATriggerDestroySummon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DestroySummon_P_Yugiri_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DestroySummon_P_Yugiri_C")
	}
	static class UBP_DestroySummon_P_Yugiri_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DestroySummon_P_Yugiri_C>();
	}
};
DUMPER7_ASSERTS_UBP_DestroySummon_P_Yugiri_C;

}

