#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_G28_DamageType

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_G28_DamageType.BP_G28_DamageType_C
// 0x0000 (0x05B0 - 0x05B0)
class UBP_G28_DamageType_C final : public UPMDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_G28_DamageType_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_G28_DamageType_C")
	}
	static class UBP_G28_DamageType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_G28_DamageType_C>();
	}
};
DUMPER7_ASSERTS_UBP_G28_DamageType_C;

}

