#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_KatanaSickle_DamageType_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_KatanaSickle_DamageType.BP_KatanaSickle_DamageType_C
// 0x0000 (0x05B0 - 0x05B0)
class BP_KatanaSickle_DamageType_0::UBP_KatanaSickle_DamageType_C : public UPMMeleeDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_KatanaSickle_DamageType.BP_KatanaSickle_DamageType_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_KatanaSickle_DamageType_C")
	}
	static class BP_KatanaSickle_DamageType_0::UBP_KatanaSickle_DamageType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_KatanaSickle_DamageType_0::UBP_KatanaSickle_DamageType_C>();
	}
};
DUMPER7_ASSERTS_BP_KatanaSickle_DamageType_0__UBP_KatanaSickle_DamageType_C;

}

