#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerState_TeamMatch

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerState_TeamMatch.BP_PlayerState_TeamMatch_C
// 0x0050 (0x24E0 - 0x2490)
class ABP_PlayerState_TeamMatch_C final : public APMPlayerState_TeamDeath_Two
{
public:
	class UBP_PlayerStateDataCollection_C*        BP_PlayerStateDataCollection;                      // 0x2490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyCustomModePlayerComponent*           CyCustomModePlayer;                                // 0x2498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PlayerStateSkillDataCollection_C*   BP_PlayerStateSkillDataCollection;                 // 0x24A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyPStateRoleSelectAfter*               CyPStateRoleSelectAfter;                           // 0x24A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyPStateGameEnd*                       CyPStateGameEnd;                                   // 0x24B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyPStateHalfEnterAIHosting*            CyPStateHalfEnterAIHosting;                        // 0x24B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyPStateHalfEnterRoleSelect*           CyPStateHalfEnterRoleSelect;                       // 0x24C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyPStateNone*                          CyPStateNone;                                      // 0x24C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x24D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerState_TeamMatch_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerState_TeamMatch_C")
	}
	static class ABP_PlayerState_TeamMatch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlayerState_TeamMatch_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlayerState_TeamMatch_C;

}

