#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupArmorEnemy

#include "Basic.hpp"

#include "BP_PickupArmor_Template_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PickupArmorEnemy.BP_PickupArmorEnemy_C
// 0x0000 (0x0750 - 0x0750)
class ABP_PickupArmorEnemy_C final : public ABP_PickupArmor_Template_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupArmorEnemy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupArmorEnemy_C")
	}
	static class ABP_PickupArmorEnemy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupArmorEnemy_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupArmorEnemy_C;

}

