#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PMDangerAreaDamageType

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PMDangerAreaDamageType.BP_PMDangerAreaDamageType_C
// 0x0000 (0x05B0 - 0x05B0)
class UBP_PMDangerAreaDamageType_C final : public UPMDangerZoneDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PMDangerAreaDamageType_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PMDangerAreaDamageType_C")
	}
	static class UBP_PMDangerAreaDamageType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PMDangerAreaDamageType_C>();
	}
};
DUMPER7_ASSERTS_UBP_PMDangerAreaDamageType_C;

}

