#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupDevourEnergy

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PickupDevourEnergy.BP_PickupDevourEnergy_C
// 0x0010 (0x0778 - 0x0768)
class BP_PickupDevourEnergy::ABP_PickupDevourEnergy_C final : public ACyPickupSphereActor
{
public:
	class UCyPickupDevourEnergy*                  CyPickupDevourEnergy;                              // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPB_PickMovement_C*                     PB_PickMovement;                                   // 0x0770(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_PickupDevourEnergy.BP_PickupDevourEnergy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupDevourEnergy_C")
	}
	static class BP_PickupDevourEnergy::ABP_PickupDevourEnergy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_PickupDevourEnergy::ABP_PickupDevourEnergy_C>();
	}
};
DUMPER7_ASSERTS_BP_PickupDevourEnergy__ABP_PickupDevourEnergy_C;

}

