#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PracticeAIController

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PracticeAIController.BP_PracticeAIController_C
// 0x0000 (0x06F8 - 0x06F8)
class ABP_PracticeAIController_C final : public ACyPracticeAIController
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PracticeAIController_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PracticeAIController_C")
	}
	static class ABP_PracticeAIController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PracticeAIController_C>();
	}
};
DUMPER7_ASSERTS_ABP_PracticeAIController_C;

}

