#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RealDamageType_Q_Mara

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RealDamageType_Q_Mara.BP_RealDamageType_Q_Mara_C
// 0x0000 (0x05B0 - 0x05B0)
class UBP_RealDamageType_Q_Mara_C final : public UPMRealDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RealDamageType_Q_Mara_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RealDamageType_Q_Mara_C")
	}
	static class UBP_RealDamageType_Q_Mara_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_RealDamageType_Q_Mara_C>();
	}
};
DUMPER7_ASSERTS_UBP_RealDamageType_Q_Mara_C;

}

