#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_SummonGotoState_Work

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SA_SummonGotoState_Work.BP_SA_SummonGotoState_Work_C
// 0x0000 (0x07B8 - 0x07B8)
class UBP_SA_SummonGotoState_Work_C final : public UCySAtomSummonGotoState
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_SummonGotoState_Work_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_SummonGotoState_Work_C")
	}
	static class UBP_SA_SummonGotoState_Work_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_SummonGotoState_Work_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_SummonGotoState_Work_C;

}

