#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SceneMapAreaNameActor

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SceneMapAreaNameActor.BP_SceneMapAreaNameActor_C
// 0x0010 (0x0310 - 0x0300)
class ABP_SceneMapAreaNameActor_C final : public APMSceneMapAreaNameActor
{
public:
	class UCySceneMapMaskComponent*               CySceneMapMask;                                    // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SceneMapAreaNameActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SceneMapAreaNameActor_C")
	}
	static class ABP_SceneMapAreaNameActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SceneMapAreaNameActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_SceneMapAreaNameActor_C;

}

