#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAtom_DeathProtect_X_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SAtom_DeathProtect_X.BP_SAtom_DeathProtect_X_C
// 0x0000 (0x05B8 - 0x05B8)
class BP_SAtom_DeathProtect_X_0::UBP_SAtom_DeathProtect_X_C final : public UCyStateAtomProtect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SAtom_DeathProtect_X.BP_SAtom_DeathProtect_X_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAtom_DeathProtect_X_C")
	}
	static class BP_SAtom_DeathProtect_X_0::UBP_SAtom_DeathProtect_X_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SAtom_DeathProtect_X_0::UBP_SAtom_DeathProtect_X_C>();
	}
};
DUMPER7_ASSERTS_BP_SAtom_DeathProtect_X_0__UBP_SAtom_DeathProtect_X_C;

}

