#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_SummonGotoState_Wait

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SA_SummonGotoState_Wait.BP_SA_SummonGotoState_Wait_C
// 0x0000 (0x07B8 - 0x07B8)
class BP_SA_SummonGotoState_Wait::UBP_SA_SummonGotoState_Wait_C final : public UCySAtomSummonGotoState
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SA_SummonGotoState_Wait.BP_SA_SummonGotoState_Wait_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_SummonGotoState_Wait_C")
	}
	static class BP_SA_SummonGotoState_Wait::UBP_SA_SummonGotoState_Wait_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SA_SummonGotoState_Wait::UBP_SA_SummonGotoState_Wait_C>();
	}
};
DUMPER7_ASSERTS_BP_SA_SummonGotoState_Wait__UBP_SA_SummonGotoState_Wait_C;

}

