#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SSAtom_AddForceMove

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SSAtom_AddForceMove.BP_SSAtom_AddForceMove_C
// 0x0000 (0x02A0 - 0x02A0)
class BP_SSAtom_AddForceMove::UBP_SSAtom_AddForceMove_C final : public UCySSAtomAddForceMove
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SSAtom_AddForceMove.BP_SSAtom_AddForceMove_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SSAtom_AddForceMove_C")
	}
	static class BP_SSAtom_AddForceMove::UBP_SSAtom_AddForceMove_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SSAtom_AddForceMove::UBP_SSAtom_AddForceMove_C>();
	}
};
DUMPER7_ASSERTS_BP_SSAtom_AddForceMove__UBP_SSAtom_AddForceMove_C;

}

