#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StateAtom_LookAtKillerWhenDeath

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StateAtom_LookAtKillerWhenDeath.BP_StateAtom_LookAtKillerWhenDeath_C
// 0x0000 (0x0600 - 0x0600)
class UBP_StateAtom_LookAtKillerWhenDeath_C final : public UCySAtomLookAtKillerWhenDeath
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_StateAtom_LookAtKillerWhenDeath_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_StateAtom_LookAtKillerWhenDeath_C")
	}
	static class UBP_StateAtom_LookAtKillerWhenDeath_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_StateAtom_LookAtKillerWhenDeath_C>();
	}
};
DUMPER7_ASSERTS_UBP_StateAtom_LookAtKillerWhenDeath_C;

}

