#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SADistanceMonitor_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SADistanceMonitor.BP_SADistanceMonitor_C
// 0x0000 (0x05E0 - 0x05E0)
class BP_SADistanceMonitor_0::UBP_SADistanceMonitor_C final : public UCySASummonDistanceMonitor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SADistanceMonitor.BP_SADistanceMonitor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SADistanceMonitor_C")
	}
	static class BP_SADistanceMonitor_0::UBP_SADistanceMonitor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SADistanceMonitor_0::UBP_SADistanceMonitor_C>();
	}
};
DUMPER7_ASSERTS_BP_SADistanceMonitor_0__UBP_SADistanceMonitor_C;

}

