#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAtom_GiveAttackTargetEffect

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SAtom_GiveAttackTargetEffect.BP_SAtom_GiveAttackTargetEffect_C
// 0x0000 (0x05C8 - 0x05C8)
class BP_SAtom_GiveAttackTargetEffect::UBP_SAtom_GiveAttackTargetEffect_C final : public UCySAtomInstigatorAttackWithEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SAtom_GiveAttackTargetEffect.BP_SAtom_GiveAttackTargetEffect_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAtom_GiveAttackTargetEffect_C")
	}
	static class BP_SAtom_GiveAttackTargetEffect::UBP_SAtom_GiveAttackTargetEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SAtom_GiveAttackTargetEffect::UBP_SAtom_GiveAttackTargetEffect_C>();
	}
};
DUMPER7_ASSERTS_BP_SAtom_GiveAttackTargetEffect__UBP_SAtom_GiveAttackTargetEffect_C;

}

