#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_ModifyCompProperty_Appear_Mara

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SA_ModifyCompProperty_Appear_Mara.BP_SA_ModifyCompProperty_Appear_Mara_C
// 0x0000 (0x0898 - 0x0898)
class UBP_SA_ModifyCompProperty_Appear_Mara_C final : public UCyStateAtomModifyCompProperty
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_ModifyCompProperty_Appear_Mara_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_ModifyCompProperty_Appear_Mara_C")
	}
	static class UBP_SA_ModifyCompProperty_Appear_Mara_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_ModifyCompProperty_Appear_Mara_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_ModifyCompProperty_Appear_Mara_C;

}

