#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAPlayInGameVoice_Q_Leona

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SAPlayInGameVoice_Q_Leona.BP_SAPlayInGameVoice_Q_Leona_C
// 0x0000 (0x0590 - 0x0590)
class UBP_SAPlayInGameVoice_Q_Leona_C final : public UCySAtomPlayInGameVoice
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SAPlayInGameVoice_Q_Leona_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAPlayInGameVoice_Q_Leona_C")
	}
	static class UBP_SAPlayInGameVoice_Q_Leona_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SAPlayInGameVoice_Q_Leona_C>();
	}
};
DUMPER7_ASSERTS_UBP_SAPlayInGameVoice_Q_Leona_C;

}

