#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_AddForceMove_ArousalThree_Leona

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SA_AddForceMove_ArousalThree_Leona.BP_SA_AddForceMove_ArousalThree_Leona_C
// 0x0000 (0x05B0 - 0x05B0)
class UBP_SA_AddForceMove_ArousalThree_Leona_C final : public UCySAtomAddForceUpVector
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_AddForceMove_ArousalThree_Leona_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_AddForceMove_ArousalThree_Leona_C")
	}
	static class UBP_SA_AddForceMove_ArousalThree_Leona_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_AddForceMove_ArousalThree_Leona_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_AddForceMove_ArousalThree_Leona_C;

}

