#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_ParticleScale_WorkSphere_5

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SA_ParticleScale_WorkSphere_5.BP_SA_ParticleScale_WorkSphere_5_C
// 0x0000 (0x0678 - 0x0678)
class UBP_SA_ParticleScale_WorkSphere_5_C final : public UCySAtomParticleScale
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_ParticleScale_WorkSphere_5_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_ParticleScale_WorkSphere_5_C")
	}
	static class UBP_SA_ParticleScale_WorkSphere_5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_ParticleScale_WorkSphere_5_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_ParticleScale_WorkSphere_5_C;

}

