#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TriggerAddEffects_P_MoBai_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TriggerAddEffects_P_MoBai.BP_TriggerAddEffects_P_MoBai_C
// 0x0000 (0x02A8 - 0x02A8)
class BP_TriggerAddEffects_P_MoBai_0::UBP_TriggerAddEffects_P_MoBai_C final : public UCyGATriggerAddGameplayEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TriggerAddEffects_P_MoBai.BP_TriggerAddEffects_P_MoBai_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TriggerAddEffects_P_MoBai_C")
	}
	static class BP_TriggerAddEffects_P_MoBai_0::UBP_TriggerAddEffects_P_MoBai_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TriggerAddEffects_P_MoBai_0::UBP_TriggerAddEffects_P_MoBai_C>();
	}
};
DUMPER7_ASSERTS_BP_TriggerAddEffects_P_MoBai_0__UBP_TriggerAddEffects_P_MoBai_C;

}

