#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetDetectorViewTarget

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TargetDetectorViewTarget.BP_TargetDetectorViewTarget_C
// 0x0000 (0x05D0 - 0x05D0)
class BP_TargetDetectorViewTarget::UBP_TargetDetectorViewTarget_C final : public UCyTargetDetectorViewTarget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TargetDetectorViewTarget.BP_TargetDetectorViewTarget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TargetDetectorViewTarget_C")
	}
	static class BP_TargetDetectorViewTarget::UBP_TargetDetectorViewTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TargetDetectorViewTarget::UBP_TargetDetectorViewTarget_C>();
	}
};
DUMPER7_ASSERTS_BP_TargetDetectorViewTarget__UBP_TargetDetectorViewTarget_C;

}

