#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Trigger_SpawnSummon_ArousalOne

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Trigger_SpawnSummon_ArousalOne.BP_Trigger_SpawnSummon_ArousalOne_C
// 0x0000 (0x0250 - 0x0250)
class UBP_Trigger_SpawnSummon_ArousalOne_C final : public UCyGATriggerSpawnSummonOnTarget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Trigger_SpawnSummon_ArousalOne_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Trigger_SpawnSummon_ArousalOne_C")
	}
	static class UBP_Trigger_SpawnSummon_ArousalOne_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Trigger_SpawnSummon_ArousalOne_C>();
	}
};
DUMPER7_ASSERTS_UBP_Trigger_SpawnSummon_ArousalOne_C;

}

