#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Tentacle_DamageType

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Tentacle_DamageType.BP_Tentacle_DamageType_C
// 0x0000 (0x05B0 - 0x05B0)
class BP_Tentacle_DamageType::UBP_Tentacle_DamageType_C final : public UPMMeleeDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Tentacle_DamageType.BP_Tentacle_DamageType_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Tentacle_DamageType_C")
	}
	static class BP_Tentacle_DamageType::UBP_Tentacle_DamageType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Tentacle_DamageType::UBP_Tentacle_DamageType_C>();
	}
};
DUMPER7_ASSERTS_BP_Tentacle_DamageType__UBP_Tentacle_DamageType_C;

}

