#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPSA_MoveToOnWallSummon_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPSA_MoveToOnWallSummon.BPSA_MoveToOnWallSummon_C
// 0x0000 (0x0640 - 0x0640)
class BPSA_MoveToOnWallSummon_0::UBPSA_MoveToOnWallSummon_C final : public UCySAtomMoveToOnWallTarget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BPSA_MoveToOnWallSummon.BPSA_MoveToOnWallSummon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPSA_MoveToOnWallSummon_C")
	}
	static class BPSA_MoveToOnWallSummon_0::UBPSA_MoveToOnWallSummon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BPSA_MoveToOnWallSummon_0::UBPSA_MoveToOnWallSummon_C>();
	}
};
DUMPER7_ASSERTS_BPSA_MoveToOnWallSummon_0__UBPSA_MoveToOnWallSummon_C;

}

