#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Calculation_KillSelf_Fissioner1

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Calculation_KillSelf_Fissioner1.Calculation_KillSelf_Fissioner1_C
// 0x0000 (0x0130 - 0x0130)
class UCalculation_KillSelf_Fissioner1_C final : public UCyCalculationWithAttributes
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Calculation_KillSelf_Fissioner1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Calculation_KillSelf_Fissioner1_C")
	}
	static class UCalculation_KillSelf_Fissioner1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCalculation_KillSelf_Fissioner1_C>();
	}
};
DUMPER7_ASSERTS_UCalculation_KillSelf_Fissioner1_C;

}

