#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CyGC_Lawine_ArousalThree_XRay

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CyGC_Lawine_ArousalThree_XRay.CyGC_Lawine_ArousalThree_XRay_C
// 0x0008 (0x04B8 - 0x04B0)
class ACyGC_Lawine_ArousalThree_XRay_C final : public ACyCueNotifyActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CyGC_Lawine_ArousalThree_XRay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CyGC_Lawine_ArousalThree_XRay_C")
	}
	static class ACyGC_Lawine_ArousalThree_XRay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACyGC_Lawine_ArousalThree_XRay_C>();
	}
};
DUMPER7_ASSERTS_ACyGC_Lawine_ArousalThree_XRay_C;

}

