#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_CareerRankProgressBar

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Enum_CareerRankProgressBar.Enum_CareerRankProgressBar
// NumValues: 0x0008
enum class Enum_CareerRankProgressBar : uint8
{
	NewEnumerator10                          = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator8                           = 4,
	NewEnumerator3                           = 5,
	NewEnumerator9                           = 6,
	Enum_MAX                                 = 7,
};

}

