#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Envi_Ice_Programer

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Envi_Ice_Programer.Envi_Ice_Programer_C
// 0x0000 (0x02D8 - 0x02D8)
class AEnvi_Ice_Programer_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Envi_Ice_Programer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Envi_Ice_Programer_C")
	}
	static class AEnvi_Ice_Programer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEnvi_Ice_Programer_C>();
	}
};
DUMPER7_ASSERTS_AEnvi_Ice_Programer_C;

}

