#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_X_Audery

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_X_Audery.GA_X_Audery_C
// 0x0008 (0x1AF0 - 0x1AE8)
class GA_X_Audery::UGA_X_Audery_C final : public UCyBaseAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1AE8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_X_Audery(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass GA_X_Audery.GA_X_Audery_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_X_Audery_C")
	}
	static class GA_X_Audery::UGA_X_Audery_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<GA_X_Audery::UGA_X_Audery_C>();
	}
};
DUMPER7_ASSERTS_GA_X_Audery__UGA_X_Audery_C;

}

