#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_ActionRewardEffectTwo

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_ActionRewardEffectTwo.GC_ActionRewardEffectTwo_C
// 0x0008 (0x04B8 - 0x04B0)
class AGC_ActionRewardEffectTwo_C final : public ACyCueNotifyActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_ActionRewardEffectTwo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_ActionRewardEffectTwo_C")
	}
	static class AGC_ActionRewardEffectTwo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_ActionRewardEffectTwo_C>();
	}
};
DUMPER7_ASSERTS_AGC_ActionRewardEffectTwo_C;

}

