#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_WaterPoloExposeWeaknesses

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_WaterPoloExposeWeaknesses.GC_WaterPoloExposeWeaknesses_C
// 0x0008 (0x0468 - 0x0460)
class AGC_WaterPoloExposeWeaknesses_C final : public APMGCWaterPoloExposeWeaknesses
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_WaterPoloExposeWeaknesses_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_WaterPoloExposeWeaknesses_C")
	}
	static class AGC_WaterPoloExposeWeaknesses_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_WaterPoloExposeWeaknesses_C>();
	}
};
DUMPER7_ASSERTS_AGC_WaterPoloExposeWeaknesses_C;

}

