#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_WaterPolo

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_WaterPolo.GC_WaterPolo_C
// 0x0008 (0x0340 - 0x0338)
class AGC_WaterPolo_C final : public APMGCWaterPolo
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_WaterPolo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_WaterPolo_C")
	}
	static class AGC_WaterPolo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_WaterPolo_C>();
	}
};
DUMPER7_ASSERTS_AGC_WaterPolo_C;

}

