#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Payload_InEscortArea_Infinite

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Payload_InEscortArea_Infinite.GE_Payload_InEscortArea_Infinite_C
// 0x0000 (0x10D8 - 0x10D8)
class UGE_Payload_InEscortArea_Infinite_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Payload_InEscortArea_Infinite_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Payload_InEscortArea_Infinite_C")
	}
	static class UGE_Payload_InEscortArea_Infinite_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Payload_InEscortArea_Infinite_C>();
	}
};
DUMPER7_ASSERTS_UGE_Payload_InEscortArea_Infinite_C;

}

