#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Preview_Q_Reiichi_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Preview_Q_Reiichi.Preview_Q_Reiichi_C
// 0x0050 (0x0890 - 0x0840)
class Preview_Q_Reiichi_0::APreview_Q_Reiichi_C final : public ACySummonActor
{
public:
	uint8                                         Pad_838[0x8];                                      // 0x0838(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0840(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySceneMapTwoPointLineReiichiPreviewComponent* CySceneMapTwoPointLineReiichiPreview;      // 0x0848(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyPreviewReiichiSummonComponent*       CyPreviewReiichiSummon;                            // 0x0850(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 MainSkeletalMesh;                                  // 0x0858(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySkinComponent*                       CySkin;                                            // 0x0860(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        EndScene;                                          // 0x0868(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        StartScene;                                        // 0x0870(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0878(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0880(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Preview_Q_Reiichi.Preview_Q_Reiichi_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Preview_Q_Reiichi_C")
	}
	static class Preview_Q_Reiichi_0::APreview_Q_Reiichi_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Preview_Q_Reiichi_0::APreview_Q_Reiichi_C>();
	}
};
DUMPER7_ASSERTS_Preview_Q_Reiichi_0__APreview_Q_Reiichi_C;

}

