#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_ArousalThree_Lawine

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_ArousalThree_Lawine.Projectile_ArousalThree_Lawine_C
// 0x0008 (0x0AD0 - 0x0AC8)
class Projectile_ArousalThree_Lawine::AProjectile_ArousalThree_Lawine_C final : public ACyProjectileBlast
{
public:
	class UCyRetainComponent*                     CyRetain;                                          // 0x0AC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Projectile_ArousalThree_Lawine.Projectile_ArousalThree_Lawine_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile_ArousalThree_Lawine_C")
	}
	static class Projectile_ArousalThree_Lawine::AProjectile_ArousalThree_Lawine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Projectile_ArousalThree_Lawine::AProjectile_ArousalThree_Lawine_C>();
	}
};
DUMPER7_ASSERTS_Projectile_ArousalThree_Lawine__AProjectile_ArousalThree_Lawine_C;

}

