#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_ArousalTwo_Chiyo

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_ArousalTwo_Chiyo.Projectile_ArousalTwo_Chiyo_C
// 0x0008 (0x0AD0 - 0x0AC8)
class AProjectile_ArousalTwo_Chiyo_C final : public ACyProjectileBlast
{
public:
	class UCyRetainComponent*                     CyRetain;                                          // 0x0AC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Projectile_ArousalTwo_Chiyo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile_ArousalTwo_Chiyo_C")
	}
	static class AProjectile_ArousalTwo_Chiyo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_ArousalTwo_Chiyo_C>();
	}
};
DUMPER7_ASSERTS_AProjectile_ArousalTwo_Chiyo_C;

}

