#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_E_Audery

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_E_Audery.Projectile_E_Audery_C
// 0x0018 (0x0AE0 - 0x0AC8)
class Projectile_E_Audery::AProjectile_E_Audery_C final : public ACyProjectileBlast
{
public:
	class UBP_GameStateComponent_Summon_C*        BP_GameStateComponent_Summon;                      // 0x0AC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyRetainComponent*                     CyRetain;                                          // 0x0AD0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyDataManagerComponent*                CyDataManager;                                     // 0x0AD8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Projectile_E_Audery.Projectile_E_Audery_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile_E_Audery_C")
	}
	static class Projectile_E_Audery::AProjectile_E_Audery_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Projectile_E_Audery::AProjectile_E_Audery_C>();
	}
};
DUMPER7_ASSERTS_Projectile_E_Audery__AProjectile_E_Audery_C;

}

