#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_E_Summon_Audery

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_E_Summon_Audery.Projectile_E_Summon_Audery_C
// 0x0010 (0x0B20 - 0x0B10)
class AProjectile_E_Summon_Audery_C final : public ACyProjectileBlast
{
public:
	class UCyRetainComponent*                     CyRetain;                                          // 0x0B10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkComponent*                           Ak;                                                // 0x0B18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Projectile_E_Summon_Audery_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile_E_Summon_Audery_C")
	}
	static class AProjectile_E_Summon_Audery_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_E_Summon_Audery_C>();
	}
};
DUMPER7_ASSERTS_AProjectile_E_Summon_Audery_C;

}

