#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Summon_X_Nobunaga_Scan

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Summon_X_Nobunaga_Scan.Summon_X_Nobunaga_Scan_C
// 0x0050 (0x0890 - 0x0840)
class Summon_X_Nobunaga_Scan::ASummon_X_Nobunaga_Scan_C final : public ACySummonActor
{
public:
	uint8                                         Pad_838[0x8];                                      // 0x0838(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UCyAIWorkState*                         CyAIWorkState;                                     // 0x0840(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyAbilitySystemComponent*              CyAbilitySystem;                                   // 0x0848(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_GameStateComponent_Summon_C*        BP_GameStateComponent_Summon;                      // 0x0850(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySearchTargetsComponent*              CySearchTargets;                                   // 0x0858(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyAIState*                             CyAIStateNone;                                     // 0x0860(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyAIDeathState*                        CyAIDeathState;                                    // 0x0868(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyAIMachine*                           CyAIMachine;                                       // 0x0870(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySkinComponent*                       CySkin;                                            // 0x0878(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0880(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Summon_X_Nobunaga_Scan.Summon_X_Nobunaga_Scan_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Summon_X_Nobunaga_Scan_C")
	}
	static class Summon_X_Nobunaga_Scan::ASummon_X_Nobunaga_Scan_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Summon_X_Nobunaga_Scan::ASummon_X_Nobunaga_Scan_C>();
	}
};
DUMPER7_ASSERTS_Summon_X_Nobunaga_Scan__ASummon_X_Nobunaga_Scan_C;

}

