#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Summon_X_Huixing_LocationActor_0

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Summon_X_Huixing_LocationActor.Summon_X_Huixing_LocationActor_C
// 0x0020 (0x07B0 - 0x0790)
class Summon_X_Huixing_LocationActor_0::ASummon_X_Huixing_LocationActor_C final : public ACySummonActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0790(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_GameStateComponent_Summon_C*        BP_GameStateComponent_Summon;                      // 0x0798(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x07A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_Summon_X_Huixing_LocationActor(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Summon_X_Huixing_LocationActor.Summon_X_Huixing_LocationActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Summon_X_Huixing_LocationActor_C")
	}
	static class Summon_X_Huixing_LocationActor_0::ASummon_X_Huixing_LocationActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Summon_X_Huixing_LocationActor_0::ASummon_X_Huixing_LocationActor_C>();
	}
};
DUMPER7_ASSERTS_Summon_X_Huixing_LocationActor_0__ASummon_X_Huixing_LocationActor_C;

}

