#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Summon_Q_Lawine

#include "Basic.hpp"


namespace SDK::Params
{

// Function Summon_Q_Lawine.Summon_Q_Lawine_C.ExecuteUbergraph_Summon_Q_Lawine
// 0x0004 (0x0004 - 0x0000)
struct Summon_Q_Lawine_C_ExecuteUbergraph_Summon_Q_Lawine final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Summon_Q_Lawine_C_ExecuteUbergraph_Summon_Q_Lawine;

}

