#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RankBadgeLvEff

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_RankBadgeLvEff.WBP_RankBadgeLvEff_C.ExecuteUbergraph_WBP_RankBadgeLvEff
// 0x0004 (0x0004 - 0x0000)
struct WBP_RankBadgeLvEff_C_ExecuteUbergraph_WBP_RankBadgeLvEff final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_RankBadgeLvEff_C_ExecuteUbergraph_WBP_RankBadgeLvEff;

}

