#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CampusActivities_ResultPage

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CampusActivities_ResultPage.WBP_CampusActivities_ResultPage_C
// 0x0020 (0x05E8 - 0x05C8)
class UWBP_CampusActivities_ResultPage_C final : public UPMBaseUserWidget
{
public:
	class UListView*                              ListTag;                                           // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        Switcher_CampText;                                 // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPMTextBlock*                           Text_ContributionValue;                            // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPMTextBlock*                           Text_Score;                                        // 0x05E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CampusActivities_ResultPage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CampusActivities_ResultPage_C")
	}
	static class UWBP_CampusActivities_ResultPage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CampusActivities_ResultPage_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CampusActivities_ResultPage_C;

}

