#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatPlayerHead

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ChatPlayerHead.WBP_ChatPlayerHead_C
// 0x0010 (0x08D0 - 0x08C0)
class UWBP_ChatPlayerHead_C final : public UPMUserWidget
{
public:
	class UImage*                                 Image_PlayerBorder;                                // 0x08C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_PlayerIcon;                                  // 0x08C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ChatPlayerHead_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ChatPlayerHead_C")
	}
	static class UWBP_ChatPlayerHead_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ChatPlayerHead_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ChatPlayerHead_C;

}

