#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GrowthWakeLevel_Retrofit3

#include "Basic.hpp"

#include "WBP_GrowthWakeLevel_Retrofit3_classes.hpp"
#include "WBP_GrowthWakeLevel_Retrofit3_parameters.hpp"


namespace SDK
{

// Function WBP_GrowthWakeLevel_Retrofit3.WBP_GrowthWakeLevel_Retrofit3_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_GrowthWakeLevel_Retrofit3_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GrowthWakeLevel_Retrofit3_C", "PreConstruct");

	Params::WBP_GrowthWakeLevel_Retrofit3_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GrowthWakeLevel_Retrofit3.WBP_GrowthWakeLevel_Retrofit3_C.ExecuteUbergraph_WBP_GrowthWakeLevel_Retrofit3
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GrowthWakeLevel_Retrofit3_C::ExecuteUbergraph_WBP_GrowthWakeLevel_Retrofit3(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GrowthWakeLevel_Retrofit3_C", "ExecuteUbergraph_WBP_GrowthWakeLevel_Retrofit3");

	Params::WBP_GrowthWakeLevel_Retrofit3_C_ExecuteUbergraph_WBP_GrowthWakeLevel_Retrofit3 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

