#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IconFeedbackContainerPage

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_IconFeedbackContainerPage.WBP_IconFeedbackContainerPage_C
// 0x0008 (0x0B70 - 0x0B68)
class UWBP_IconFeedbackContainerPage_C final : public UCyUWIconFeedbackContainerPagePC
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B68(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	class UTextureRenderTarget2D* TryBlueprintExport(float InDeltaTime, const struct FVector2D& InOutSize);
	void TryToExportRT_PNG(class UTextureRenderTarget2D* InRT, const struct FVector2D& InOutSize, int32 PathKeyIndex, int32 OutputIndex);
	void ExecuteUbergraph_WBP_IconFeedbackContainerPage(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_IconFeedbackContainerPage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_IconFeedbackContainerPage_C")
	}
	static class UWBP_IconFeedbackContainerPage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_IconFeedbackContainerPage_C>();
	}
};
DUMPER7_ASSERTS_UWBP_IconFeedbackContainerPage_C;

}

