#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SelectRoleLoadingScrollBarItem

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SelectRoleLoadingScrollBarItem.WBP_SelectRoleLoadingScrollBarItem_C
// 0x0018 (0x05E0 - 0x05C8)
class UWBP_SelectRoleLoadingScrollBarItem_C final : public UPMBaseUserWidget
{
public:
	class UImage*                                 Image;                                             // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_200;                                         // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher;                                    // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SelectRoleLoadingScrollBarItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SelectRoleLoadingScrollBarItem_C")
	}
	static class UWBP_SelectRoleLoadingScrollBarItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SelectRoleLoadingScrollBarItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SelectRoleLoadingScrollBarItem_C;

}

