#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ModeFeedbackTipsPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ModeFeedbackTipsPanel.WBP_ModeFeedbackTipsPanel_C
// 0x0010 (0x0B10 - 0x0B00)
class UWBP_ModeFeedbackTipsPanel_C final : public UCyUWFeedbackTipsMonitorPanel
{
public:
	class UImage*                                 Img;                                               // 0x0B00(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UInvalidationBox*                       InvalidationBox_3;                                 // 0x0B08(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ModeFeedbackTipsPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ModeFeedbackTipsPanel_C")
	}
	static class UWBP_ModeFeedbackTipsPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ModeFeedbackTipsPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ModeFeedbackTipsPanel_C;

}

