#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RankStarFill

#include "Basic.hpp"

#include "WBP_RankStarFill_classes.hpp"
#include "WBP_RankStarFill_parameters.hpp"


namespace SDK
{

// Function WBP_RankStarFill.WBP_RankStarFill_C.ExecuteUbergraph_WBP_RankStarFill
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RankStarFill_C::ExecuteUbergraph_WBP_RankStarFill(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RankStarFill_C", "ExecuteUbergraph_WBP_RankStarFill");

	Params::WBP_RankStarFill_C_ExecuteUbergraph_WBP_RankStarFill Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RankStarFill.WBP_RankStarFill_C.SetIsFilled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bFill                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_RankStarFill_C::SetIsFilled(bool bFill)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RankStarFill_C", "SetIsFilled");

	Params::WBP_RankStarFill_C_SetIsFilled Parms{};

	Parms.bFill = bFill;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RankStarFill.WBP_RankStarFill_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_RankStarFill_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RankStarFill_C", "PreConstruct");

	Params::WBP_RankStarFill_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

