#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SelectRoleRoomInfo

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SelectRoleRoomInfo.WBP_SelectRoleRoomInfo_C
// 0x0018 (0x08D8 - 0x08C0)
class UWBP_SelectRoleRoomInfo_C final : public UPMUserWidget
{
public:
	class UImage*                                 Image_49;                                          // 0x08C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_MapName;                                 // 0x08C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_RoomType;                                // 0x08D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SelectRoleRoomInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SelectRoleRoomInfo_C")
	}
	static class UWBP_SelectRoleRoomInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SelectRoleRoomInfo_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SelectRoleRoomInfo_C;

}

