#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TitlePage

#include "Basic.hpp"

#include "WBP_TitlePage_classes.hpp"
#include "WBP_TitlePage_parameters.hpp"


namespace SDK
{

// Function WBP_TitlePage.WBP_TitlePage_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TitlePage_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TitlePage_C", "PreConstruct");

	Params::WBP_TitlePage_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TitlePage.WBP_TitlePage_C.ExecuteUbergraph_WBP_TitlePage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TitlePage_C::ExecuteUbergraph_WBP_TitlePage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TitlePage_C", "ExecuteUbergraph_WBP_TitlePage");

	Params::WBP_TitlePage_C_ExecuteUbergraph_WBP_TitlePage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

