#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DecalWheelItem

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_DecalWheelItem.WBP_DecalWheelItem_C
// 0x0010 (0x0920 - 0x0910)
class UWBP_DecalWheelItem_C final : public UCyUWDecalWheelPanelItem
{
public:
	class UImage*                                 Img_Icon;                                          // 0x0910(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_Num;                                           // 0x0918(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_DecalWheelItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_DecalWheelItem_C")
	}
	static class UWBP_DecalWheelItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DecalWheelItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_DecalWheelItem_C;

}

