#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EmotionItem

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_EmotionItem.WBP_EmotionItem_C
// 0x0090 (0x06B8 - 0x0628)
class UWBP_EmotionItem_C final : public UPMBaseWidgetItem
{
public:
	class UPMImage*                               Img_Emote;                                         // 0x0628(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FSlateBrush                            Image;                                             // 0x0630(0x0088)(Edit, BlueprintVisible)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_EmotionItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_EmotionItem_C")
	}
	static class UWBP_EmotionItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EmotionItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_EmotionItem_C;

}

