#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EquipRoomStory_PersonalInfoItem

#include "Basic.hpp"

#include "WBP_EquipRoomStory_PersonalInfoItem_classes.hpp"
#include "WBP_EquipRoomStory_PersonalInfoItem_parameters.hpp"


namespace SDK
{

// Function WBP_EquipRoomStory_PersonalInfoItem.WBP_EquipRoomStory_PersonalInfoItem_C.ExecuteUbergraph_WBP_EquipRoomStory_PersonalInfoItem
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_EquipRoomStory_PersonalInfoItem_C::ExecuteUbergraph_WBP_EquipRoomStory_PersonalInfoItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EquipRoomStory_PersonalInfoItem_C", "ExecuteUbergraph_WBP_EquipRoomStory_PersonalInfoItem");

	Params::WBP_EquipRoomStory_PersonalInfoItem_C_ExecuteUbergraph_WBP_EquipRoomStory_PersonalInfoItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EquipRoomStory_PersonalInfoItem.WBP_EquipRoomStory_PersonalInfoItem_C.OnListItemObjectSet
// (Native, Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_EquipRoomStory_PersonalInfoItem_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EquipRoomStory_PersonalInfoItem_C", "OnListItemObjectSet");

	Params::WBP_EquipRoomStory_PersonalInfoItem_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WBP_EquipRoomStory_PersonalInfoItem.WBP_EquipRoomStory_PersonalInfoItem_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_EquipRoomStory_PersonalInfoItem_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EquipRoomStory_PersonalInfoItem_C", "BP_OnItemSelectionChanged");

	Params::WBP_EquipRoomStory_PersonalInfoItem_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EquipRoomStory_PersonalInfoItem.WBP_EquipRoomStory_PersonalInfoItem_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_EquipRoomStory_PersonalInfoItem_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EquipRoomStory_PersonalInfoItem_C", "BP_OnItemExpansionChanged");

	Params::WBP_EquipRoomStory_PersonalInfoItem_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EquipRoomStory_PersonalInfoItem.WBP_EquipRoomStory_PersonalInfoItem_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_EquipRoomStory_PersonalInfoItem_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EquipRoomStory_PersonalInfoItem_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}

}

