#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EscortResultPage_ScorePage

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_EscortResultPage_ScorePage.WBP_EscortResultPage_ScorePage_C.Get_TextBlock_Mode_Text_0
// 0x0018 (0x0018 - 0x0000)
struct WBP_EscortResultPage_ScorePage_C_Get_TextBlock_Mode_Text_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_WBP_EscortResultPage_ScorePage_C_Get_TextBlock_Mode_Text_0;

}

