#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MarkWheelItem

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MarkWheelItem.WBP_MarkWheelItem_C
// 0x0020 (0x0928 - 0x0908)
class UWBP_MarkWheelItem_C final : public UCyUWMarkWheelPanelItem
{
public:
	class UWBP_InGameKeyMappings_C*               WBP_InGameKeyMappings;                             // 0x0908(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_InGameKeyMappings_C*               WBP_InGameKeyMappings_1;                           // 0x0910(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_InGameKeyMappings_C*               WBP_InGameKeyMappings_2;                           // 0x0918(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_InGameKeyMappings_C*               WBP_InGameKeyMappings_3;                           // 0x0920(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MarkWheelItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MarkWheelItem_C")
	}
	static class UWBP_MarkWheelItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MarkWheelItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MarkWheelItem_C;

}

