#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CareerRankCombo

#include "Basic.hpp"

#include "WBP_CareerRankCombo_classes.hpp"
#include "WBP_CareerRankCombo_parameters.hpp"


namespace SDK
{

// Function WBP_CareerRankCombo.WBP_CareerRankCombo_C.ExecuteUbergraph_WBP_CareerRankCombo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CareerRankCombo_C::ExecuteUbergraph_WBP_CareerRankCombo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CareerRankCombo_C", "ExecuteUbergraph_WBP_CareerRankCombo");

	Params::WBP_CareerRankCombo_C_ExecuteUbergraph_WBP_CareerRankCombo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CareerRankCombo.WBP_CareerRankCombo_C.Construct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void UWBP_CareerRankCombo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CareerRankCombo_C", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

