#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Growth_EquipWeaponList1

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Growth_EquipWeaponList1.WBP_Growth_EquipWeaponList1_C
// 0x0018 (0x08D8 - 0x08C0)
class UWBP_Growth_EquipWeaponList1_C final : public UPMUserWidget
{
public:
	class UWidgetAnimation*                       Presse;                                            // 0x08C0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Hover;                                             // 0x08C8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UPMListView*                            WeaponList;                                        // 0x08D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Growth_EquipWeaponList1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Growth_EquipWeaponList1_C")
	}
	static class UWBP_Growth_EquipWeaponList1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Growth_EquipWeaponList1_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Growth_EquipWeaponList1_C;

}

