#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InteractionPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_InteractionPanel.WBP_InteractionPanel_C
// 0x0008 (0x0C98 - 0x0C90)
class UWBP_InteractionPanel_C final : public UPMUWInteractionPanelPC
{
public:
	class UWBP_InGameKeyMappings_C*               KeyMappingPanel_Q_1;                               // 0x0C90(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InteractionPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InteractionPanel_C")
	}
	static class UWBP_InteractionPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InteractionPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InteractionPanel_C;

}

