#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MiniMapScene

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MiniMapScene.WBP_MiniMapScene_C
// 0x0000 (0x0C78 - 0x0C78)
class UWBP_MiniMapScene_C final : public UCyMiniSceneMap2D
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MiniMapScene_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MiniMapScene_C")
	}
	static class UWBP_MiniMapScene_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MiniMapScene_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MiniMapScene_C;

}

