#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CareerRankCombo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CareerRankCombo.WBP_CareerRankCombo_C
// 0x0010 (0x05D8 - 0x05C8)
class UWBP_CareerRankCombo_C final : public UPMBaseUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UListView*                              ListView_MenuContent;                              // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CareerRankCombo(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CareerRankCombo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CareerRankCombo_C")
	}
	static class UWBP_CareerRankCombo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CareerRankCombo_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CareerRankCombo_C;

}

