#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RefereeEquipmentPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_RefereeEquipmentPanel.WBP_RefereeEquipmentPanel_C
// 0x0010 (0x1030 - 0x1020)
class UWBP_RefereeEquipmentPanel_C final : public UPMUWRefereeEquipmentPanel
{
public:
	class UImage*                                 Img_Bg;                                            // 0x1020(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_RefereeEquipmentPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_RefereeEquipmentPanel_C")
	}
	static class UWBP_RefereeEquipmentPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RefereeEquipmentPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_RefereeEquipmentPanel_C;

}

