#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InventoryMeleeWeaponItem

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_InventoryMeleeWeaponItem.WBP_InventoryMeleeWeaponItem_C
// 0x0020 (0x0CF8 - 0x0CD8)
class UWBP_InventoryMeleeWeaponItem_C final : public UPMUWInventoryItemPC
{
public:
	class UWidgetAnimation*                       MeleeSelected;                                     // 0x0CD8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       UnSelected;                                        // 0x0CE0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Selected;                                          // 0x0CE8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Img_Katana;                                        // 0x0CF0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InventoryMeleeWeaponItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InventoryMeleeWeaponItem_C")
	}
	static class UWBP_InventoryMeleeWeaponItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InventoryMeleeWeaponItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InventoryMeleeWeaponItem_C;

}

