#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TeamChangeRoleTips

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TeamChangeRoleTips.WBP_TeamChangeRoleTips_C
// 0x0020 (0x0968 - 0x0948)
class UWBP_TeamChangeRoleTips_C final : public UPMTeamChangeRoleTipsPanel
{
public:
	class UTextBlock*                             TextDesc;                                          // 0x0948(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextDesc_1;                                        // 0x0950(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_RichTextKeyMappings_C*             WBP_RichTextKeyMappingsPC_1;                       // 0x0958(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_RichTextKeyMappings_C*             WBP_RichTextKeyMappingsPC_2;                       // 0x0960(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TeamChangeRoleTips_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TeamChangeRoleTips_C")
	}
	static class UWBP_TeamChangeRoleTips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TeamChangeRoleTips_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TeamChangeRoleTips_C;

}

