#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ScoreTitleTeam

#include "Basic.hpp"

#include "WBP_ScoreTitleTeam_classes.hpp"
#include "WBP_ScoreTitleTeam_parameters.hpp"


namespace SDK
{

// Function WBP_ScoreTitleTeam.WBP_ScoreTitleTeam_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_ScoreTitleTeam_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreTitleTeam_C", "PreConstruct");

	Params::WBP_ScoreTitleTeam_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ScoreTitleTeam.WBP_ScoreTitleTeam_C.ExecuteUbergraph_WBP_ScoreTitleTeam
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ScoreTitleTeam_C::ExecuteUbergraph_WBP_ScoreTitleTeam(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreTitleTeam_C", "ExecuteUbergraph_WBP_ScoreTitleTeam");

	Params::WBP_ScoreTitleTeam_C_ExecuteUbergraph_WBP_ScoreTitleTeam Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

