#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InteractionProgressBar

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_InteractionProgressBar.WBP_InteractionProgressBar_C
// 0x0000 (0x08C8 - 0x08C8)
class UWBP_InteractionProgressBar_C final : public UPMUWInteractionProgressBarPC
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InteractionProgressBar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InteractionProgressBar_C")
	}
	static class UWBP_InteractionProgressBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InteractionProgressBar_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InteractionProgressBar_C;

}

