#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TeamGrowthTipsPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TeamGrowthTipsPanel.WBP_TeamGrowthTipsPanel_C
// 0x0008 (0x0A20 - 0x0A18)
class UWBP_TeamGrowthTipsPanel_C final : public UCyUWTeamGrowthTipsPanel
{
public:
	class UWBP_RichTextKeyMappings_C*             WBP_RichTextKeyMappingsPC_4;                       // 0x0A18(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TeamGrowthTipsPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TeamGrowthTipsPanel_C")
	}
	static class UWBP_TeamGrowthTipsPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TeamGrowthTipsPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TeamGrowthTipsPanel_C;

}

