#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SelectRoleCardIllustrations

#include "Basic.hpp"

#include "WBP_SelectRoleCardIllustrations_classes.hpp"
#include "WBP_SelectRoleCardIllustrations_parameters.hpp"


namespace SDK
{

// Function WBP_SelectRoleCardIllustrations.WBP_SelectRoleCardIllustrations_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_SelectRoleCardIllustrations_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectRoleCardIllustrations_C", "PreConstruct");

	Params::WBP_SelectRoleCardIllustrations_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SelectRoleCardIllustrations.WBP_SelectRoleCardIllustrations_C.ExecuteUbergraph_WBP_SelectRoleCardIllustrations
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SelectRoleCardIllustrations_C::ExecuteUbergraph_WBP_SelectRoleCardIllustrations(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectRoleCardIllustrations_C", "ExecuteUbergraph_WBP_SelectRoleCardIllustrations");

	Params::WBP_SelectRoleCardIllustrations_C_ExecuteUbergraph_WBP_SelectRoleCardIllustrations Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

