#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Progress_Huixing_Teleport

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Progress_Huixing_Teleport.WBP_Progress_Huixing_Teleport_C
// 0x0010 (0x0A78 - 0x0A68)
class UWBP_Progress_Huixing_Teleport_C final : public UPMUWBuffFullScreenProgressPC
{
public:
	class UImage*                                 Image_12;                                          // 0x0A68(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_Buff;                                  // 0x0A70(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Progress_Huixing_Teleport_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Progress_Huixing_Teleport_C")
	}
	static class UWBP_Progress_Huixing_Teleport_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Progress_Huixing_Teleport_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Progress_Huixing_Teleport_C;

}

