#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ResultRankProgressEffect

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ResultRankProgressEffect.WBP_ResultRankProgressEffect_C
// 0x0008 (0x0268 - 0x0260)
class UWBP_ResultRankProgressEffect_C final : public UUserWidget
{
public:
	class UWidgetAnimation*                       starEffect;                                        // 0x0260(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ResultRankProgressEffect_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ResultRankProgressEffect_C")
	}
	static class UWBP_ResultRankProgressEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ResultRankProgressEffect_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ResultRankProgressEffect_C;

}

