#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GrowthWakeLevel_Retrofit

#include "Basic.hpp"

#include "WBP_GrowthWakeLevel_Retrofit_classes.hpp"
#include "WBP_GrowthWakeLevel_Retrofit_parameters.hpp"


namespace SDK
{

// Function WBP_GrowthWakeLevel_Retrofit.WBP_GrowthWakeLevel_Retrofit_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_GrowthWakeLevel_Retrofit_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GrowthWakeLevel_Retrofit_C", "PreConstruct");

	Params::WBP_GrowthWakeLevel_Retrofit_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GrowthWakeLevel_Retrofit.WBP_GrowthWakeLevel_Retrofit_C.ExecuteUbergraph_WBP_GrowthWakeLevel_Retrofit
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GrowthWakeLevel_Retrofit_C::ExecuteUbergraph_WBP_GrowthWakeLevel_Retrofit(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GrowthWakeLevel_Retrofit_C", "ExecuteUbergraph_WBP_GrowthWakeLevel_Retrofit");

	Params::WBP_GrowthWakeLevel_Retrofit_C_ExecuteUbergraph_WBP_GrowthWakeLevel_Retrofit Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

