#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ScoreTitleTeam

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_ScoreTitleTeam.WBP_ScoreTitleTeam_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_ScoreTitleTeam_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_ScoreTitleTeam_C_PreConstruct;

// Function WBP_ScoreTitleTeam.WBP_ScoreTitleTeam_C.ExecuteUbergraph_WBP_ScoreTitleTeam
// 0x0008 (0x0008 - 0x0000)
struct WBP_ScoreTitleTeam_C_ExecuteUbergraph_WBP_ScoreTitleTeam final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_ScoreTitleTeam_C_ExecuteUbergraph_WBP_ScoreTitleTeam;

}

