#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AddPointItemPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_AddPointItemPanel.WBP_AddPointItemPanel_C
// 0x0008 (0x0920 - 0x0918)
class UWBP_AddPointItemPanel_C final : public UCyUWScoreBehaviorItem
{
public:
	class UWidgetAnimation*                       Anim_MoveUp1;                                      // 0x0918(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_AddPointItemPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_AddPointItemPanel_C")
	}
	static class UWBP_AddPointItemPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AddPointItemPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_AddPointItemPanel_C;

}

