#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ResultScoreTips

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ResultScoreTips.WBP_ResultScoreTips_C
// 0x0060 (0x0920 - 0x08C0)
class UWBP_ResultScoreTips_C final : public UPMUserWidget
{
public:
	class UWidgetSwitcher*                        Switcher_Bg;                                       // 0x08C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Txt_ScoreTips;                                     // 0x08C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMap<int32, class FText>                      ScoreTipMap;                                       // 0x08D0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ResultScoreTips_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ResultScoreTips_C")
	}
	static class UWBP_ResultScoreTips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ResultScoreTips_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ResultScoreTips_C;

}

