#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HealthBar

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_HealthBar.WBP_HealthBar_C
// 0x0010 (0x0B90 - 0x0B80)
class UWBP_HealthBar_C final : public UCyUWCharacterHealthBarPC
{
public:
	class UCanvasPanel*                           CanvasPanel;                                       // 0x0B80(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UInvalidationBox*                       InvalidationBox_0;                                 // 0x0B88(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_HealthBar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_HealthBar_C")
	}
	static class UWBP_HealthBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_HealthBar_C>();
	}
};
DUMPER7_ASSERTS_UWBP_HealthBar_C;

}

