#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TriTeamFightTimePanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TriTeamFightTimePanel.WBP_TriTeamFightTimePanel_C
// 0x0008 (0x0B30 - 0x0B28)
class UWBP_TriTeamFightTimePanel_C final : public UPMUWTriRoundFightingPanelPC
{
public:
	class UCanvasPanel*                           Panel_Root;                                        // 0x0B28(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TriTeamFightTimePanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TriTeamFightTimePanel_C")
	}
	static class UWBP_TriTeamFightTimePanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TriTeamFightTimePanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TriTeamFightTimePanel_C;

}

