#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RankStarTrack

#include "Basic.hpp"

#include "WBP_RankStarTrack_classes.hpp"
#include "WBP_RankStarTrack_parameters.hpp"


namespace SDK
{

// Function WBP_RankStarTrack.WBP_RankStarTrack_C.ExecuteUbergraph_WBP_RankStarTrack
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RankStarTrack_C::ExecuteUbergraph_WBP_RankStarTrack(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RankStarTrack_C", "ExecuteUbergraph_WBP_RankStarTrack");

	Params::WBP_RankStarTrack_C_ExecuteUbergraph_WBP_RankStarTrack Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RankStarTrack.WBP_RankStarTrack_C.StarIsFront
// (Native, BlueprintCallable, BlueprintEvent)

void UWBP_RankStarTrack_C::StarIsFront()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RankStarTrack_C", "StarIsFront");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function WBP_RankStarTrack.WBP_RankStarTrack_C.StarIsBack
// (Native, BlueprintCallable, BlueprintEvent)

void UWBP_RankStarTrack_C::StarIsBack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RankStarTrack_C", "StarIsBack");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function WBP_RankStarTrack.WBP_RankStarTrack_C.SequenceEvent__ENTRYPOINTWBP_RankStarTrack_0
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_RankStarTrack_C::SequenceEvent__ENTRYPOINTWBP_RankStarTrack_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RankStarTrack_C", "SequenceEvent__ENTRYPOINTWBP_RankStarTrack_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RankStarTrack.WBP_RankStarTrack_C.SequenceEvent__ENTRYPOINTWBP_RankStarTrack_1
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_RankStarTrack_C::SequenceEvent__ENTRYPOINTWBP_RankStarTrack_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RankStarTrack_C", "SequenceEvent__ENTRYPOINTWBP_RankStarTrack_1");

	UObject::ProcessEvent(Func, nullptr);
}

}

