#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Castling_Galatea

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Castling_Galatea.Weapon_Castling_Galatea_C
// 0x0030 (0x14A0 - 0x1470)
class Weapon_Castling_Galatea::AWeapon_Castling_Galatea_C final : public ACyWeaponCustom
{
public:
	class UCySearchLocationComponent*             CySearchLocation;                                  // 0x1470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySearchTargetsComponent*              CySearchTargets;                                   // 0x1478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyFSecondWorkState*                    CyFSecondWorkState;                                // 0x1480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyTargetActorsComponent*               CyTargetActors;                                    // 0x1488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyFWorkState*                          CyFWorkState;                                      // 0x1490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Weapon_Castling_Galatea.Weapon_Castling_Galatea_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Castling_Galatea_C")
	}
	static class Weapon_Castling_Galatea::AWeapon_Castling_Galatea_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Weapon_Castling_Galatea::AWeapon_Castling_Galatea_C>();
	}
};
DUMPER7_ASSERTS_Weapon_Castling_Galatea__AWeapon_Castling_Galatea_C;

}

