#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Rescue_V2

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Rescue_V2.Weapon_Rescue_V2_C
// 0x0020 (0x11B0 - 0x1190)
class AWeapon_Rescue_V2_C final : public ACyWeaponSkill
{
public:
	class UCyFStateMonitor*                       CyFStateMonitorAddRescueTime;                      // 0x1190(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyTargetActorsComponent*               CyTargetActors;                                    // 0x1198(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyActuatorComponent*                   CyActuator;                                        // 0x11A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySpawnManagerComponent*               CySpawnManager;                                    // 0x11A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_Rescue_V2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Rescue_V2_C")
	}
	static class AWeapon_Rescue_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_Rescue_V2_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_Rescue_V2_C;

}

