#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Q_Michele_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Q_Michele.Weapon_Q_Michele_C
// 0x0010 (0x11A0 - 0x1190)
class Weapon_Q_Michele_0::AWeapon_Q_Michele_C final : public ACyWeaponQuickThrowLocation
{
public:
	class UCySearchLocationComponent*             CySearchLocation;                                  // 0x1190(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Weapon_Q_Michele.Weapon_Q_Michele_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Q_Michele_C")
	}
	static class Weapon_Q_Michele_0::AWeapon_Q_Michele_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Weapon_Q_Michele_0::AWeapon_Q_Michele_C>();
	}
};
DUMPER7_ASSERTS_Weapon_Q_Michele_0__AWeapon_Q_Michele_C;

}

