#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_X_Mara

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_X_Mara.Weapon_X_Mara_C
// 0x0020 (0x11B0 - 0x1190)
class AWeapon_X_Mara_C final : public ACyWeaponQuickThrow
{
public:
	class UCyFStateMonitor*                       CyFStateMonitor;                                   // 0x1190(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySearchLocationComponent*             CySearchLocation;                                  // 0x1198(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySpawnManagerComponent*               CySpawnManager;                                    // 0x11A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySkinComponent*                       CySkin;                                            // 0x11A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_X_Mara_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_X_Mara_C")
	}
	static class AWeapon_X_Mara_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_X_Mara_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_X_Mara_C;

}

