#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_E_Flavia

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_E_Flavia.Weapon_E_Flavia_C
// 0x0010 (0x11A0 - 0x1190)
class Weapon_E_Flavia::AWeapon_E_Flavia_C final : public ACyWeaponSkill
{
public:
	class UAkComponent*                           Ak;                                                // 0x1190(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Weapon_E_Flavia.Weapon_E_Flavia_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_E_Flavia_C")
	}
	static class Weapon_E_Flavia::AWeapon_E_Flavia_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Weapon_E_Flavia::AWeapon_E_Flavia_C>();
	}
};
DUMPER7_ASSERTS_Weapon_E_Flavia__AWeapon_E_Flavia_C;

}

