#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Q_Galatea

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Q_Galatea.Weapon_Q_Galatea_C
// 0x0010 (0x11A0 - 0x1190)
class Weapon_Q_Galatea::AWeapon_Q_Galatea_C final : public ACyWeaponQuickThrow
{
public:
	class UCySearchLocationComponent*             CySearchLocation;                                  // 0x1190(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Weapon_Q_Galatea.Weapon_Q_Galatea_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Q_Galatea_C")
	}
	static class Weapon_Q_Galatea::AWeapon_Q_Galatea_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Weapon_Q_Galatea::AWeapon_Q_Galatea_C>();
	}
};
DUMPER7_ASSERTS_Weapon_Q_Galatea__AWeapon_Q_Galatea_C;

}

