#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Q_Kanami

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_Q_Kanami.Weapon_Q_Kanami_C
// 0x0010 (0x11A0 - 0x1190)
class AWeapon_Q_Kanami_C final : public ACyWeaponQuickThrow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1190(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveTick(float DeltaSeconds);
	void ExecuteUbergraph_Weapon_Q_Kanami(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_Q_Kanami_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Q_Kanami_C")
	}
	static class AWeapon_Q_Kanami_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_Q_Kanami_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_Q_Kanami_C;

}

