#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon15202001

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon15202001.Weapon15202001_C
// 0x0000 (0x11F0 - 0x11F0)
class AWeapon15202001_C final : public ACyWeaponMelee_ExtremeKnifeFight
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon15202001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon15202001_C")
	}
	static class AWeapon15202001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon15202001_C>();
	}
};
DUMPER7_ASSERTS_AWeapon15202001_C;

}

