#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_X_Huixing_Escort2

#include "Basic.hpp"

#include "PMGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_X_Huixing_Escort2.Weapon_X_Huixing_Escort2_C
// 0x0010 (0x13B0 - 0x13A0)
class AWeapon_X_Huixing_Escort2_C final : public ACyWeaponCustom
{
public:
	class UCyFFinishState*                        CyFFinishState;                                    // 0x13A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySearchTargetsComponent*              CySearchTargets;                                   // 0x13A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_X_Huixing_Escort2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_X_Huixing_Escort2_C")
	}
	static class AWeapon_X_Huixing_Escort2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_X_Huixing_Escort2_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_X_Huixing_Escort2_C;

}

